Add support for clips4sale
timo95/stash-checker pull request #38
Opened 2024-07-01 11:00 UTC by IAmKontrast

Added studio and scene support for `clips4sale`.

**Error on icon-list-view repeated reloading:**
Unfortunately I wasn't able to solve the `Minified React error` `#418`, `#423` and `#425` on the icon-list-view on repeated reloading.
To reproduce go on one of the studio profile pages (/studio/) and then switch to the icon-list-view. Everything works fine and all checks for scenes went on. Reloading the page causes the errors.
Will be triggered by this [`check(Target.Scene, "div[class*='w-full'] a[class*='search-clip__title']", { observe: true });`](https://github.com/IAmKontrast/stash-checker/blob/a299c907614281c217ea876060d9dde4199ed7cd/src/stashChecker.ts#L373
)

2024-07-05 15:00 UTC, timo95 requested changes
I tried it without your changes and `Minified React error` still occurs, just much less often. Annoying, but not really our problem.

Please fix the overlapping Studio/Scene checks. I am using this addon to test css selectors, maybe that helps: https://addons.mozilla.org/de/firefox/addon/try-xpath/

2024-07-05 15:00 UTC, timo95 commented on src/stashChecker.ts
> +            check(Target.Studio, "div[class*='items-center'] div[class*='flex']:not([class*='hidden']) a[href*='/studio/']", {
This seems to match the title as well, resulting in additional queries that will be overwritten by studio queries. Maybe use `[data-testid*='studioAnchor'] a[href*='/studio/']` instead.

2024-07-05 15:00 UTC, timo95 commented on src/stashChecker.ts
> +            check(Target.Scene, "div[class*='w-full'] a[class*='search-clip__title']", { observe: true });
On the recently added clips page, when you scroll down below the side menu, nothing is matched. `div.w-full a.search-clip__title, div.static a.search-clip__title` would include everything.

2024-07-31 10:47 UTC, IAmKontrast commented
Completely restart my approach with element selectors from classes to `data-testid` attributes. Now there should be any additional or overriding queries and also a performance improvement is noticeable.
Maybe they fixed something on the website because the Minified React errors are gone.

> On the recently added clips page, when you scroll down below the side menu, nothing is matched.

This works now as well as switch between tile and list view and sorting.

2024-07-31 10:49 UTC, timo95 commented
> a performance improvement is noticeable

Thats just the merge from master

2024-07-31 10:51 UTC, merged

2024-07-31 14:01 UTC, IAmKontrast commented
Add a fix for studio/category matching with #46